spring.application.name=Kanatech Chamados

# Perfil padrão (local). No Render você sobrescreve via variável de ambiente.
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=${PORT:8080}

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG